### ISSUE TITLE
Proposal: add a `withElementPortal` Higher Order Component 

### ISSUE THREAD

**Issue by vitorbal** [zapier/react-element-portal#4]
It would be nice to export a [HOC](https://facebook.github.io/react/docs/higher-order-components.html) version of `ElementPortal` as well as the default Component version!

That would enable doing things like this:

```js
import { withElementPortal } from 'react-element-portal';
import { compose, connect } from 'react-redux';
import ReactDOM from 'react-dom';

const MyComponent = (props) => <h1>Hello, {props.name}!</h1>;

const MyComposedComponent = compose(
  withElementPortal(),
  connect((state) => ({ name: state.name }))
)(MyComponent);

// Somewhere in our app:
ReactDOM.render(
  <MyComponentWithPortal id="user" />,
  document.getElementById('app')
);
```

I have a suggested implementation ready here that includes tests and documentation: https://github.com/vitorbal/react-element-portal/commit/8bfddba9188a7e54b213f36e6c0b5bd1daf493d2

Let me know what you think of the idea :)

**Comment by jdeal** [comment]
@vitorbal yep, I like this addition. Are you imagining we might pass options into `withElementPortal`? If not, I'm thinking it can just be a plain HOC instead of a HOC factory like `connect`.

**Comment by vitorbal** [comment]
@jdeal Thanks for the quick feedback! 👍

I'm actually leaning more towards not taking in any options, since the props that `ElementPortal` accepts feel very "context-dependent" (e.g. the "id" to use depends very much on the tree where the portal is being rendered).

> I'm thinking it can just be a plain HOC instead of a HOC factory like connect.

Good call, I've updated the branch to make `withElementPortal` a plain HOC instead: https://github.com/vitorbal/react-element-portal/compare/8bfddba...vitorbal:hoc

Let me know what you think :)

**Comment by vitorbal** [comment]
I've added a new commit to the branch that makes `data-` attributes also be passed down when using HOC format:
https://github.com/vitorbal/react-element-portal/compare/c2d160c...vitorbal:hoc?expand=1

**Comment by jdeal** [comment]
Looks good to me!

**Comment by vitorbal** [comment]
Great, thanks! I'll open a PR for this later today 👍
