### ISSUE TITLE
What is the purpose of this?

### ISSUE THREAD

**Issue by Amberlamps** [zapier/react-element-portal#8]
What does your element solve? Why don't you just render two React applications? The example from your README can be easily solved without your module:

```
ReactDOM.render(
  <div>
      <h1>My App</h1>
      <p>This is my main app and gets rendered to #app.</p>
    </div>,
  document.getElementById('app')
);

ReactDOM.render(
        <Menu>
          <Label>Joe</Label>
          <Items>
            <Item>Upgrade</Item>
            <Item>Settings</Item>
            <Item>Support</Item>
          </Items>
        </Menu>,
  document.getElementById('user')
);
```

**Comment by ngryman** [comment]
Hey, perhaps the readme's example is misleading. I'll answer your question in 2 steps.

## The concept of portals

Portals allow you to keep the React component hierarchy without it being exactly mirrored to the DOM hierarchy. In other words, it abstracts the way you render to the DOM while keeping all the React good stuff.

In your solution, you have 2 separated React hierarchies. In very simple scenarios it can do the trick, but for a real-world usage it has several flaws:
 - How do you handle hierarchy (`App > Menu`)? More precisely how do you update `Menu` if it depends on `props` passed by the `App`?
 - How do you handle nested portals? For example, if your `Menu` is also rendering elements elsewhere? Even if it does not make sense for a `Menu`, in a real-world use case this can happen (i.e. a modal in a transported container).
 - How do you transport [context](https://reactjs.org/docs/context.html) to your transported elements?

If you have more questions about the concept of portals, some resources:
 - https://reactjs.org/docs/portals.html
 - https://github.com/tajo/react-portal

## Some handy features

This library brings some convenient features to the table:
 - Expose a component and a `hoc` for easy usage.
 - Allow handling multiple elements at the same time.
 - Helps passing data from the host DOM element to the transported React element.
